<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '詳細情報',
    'Borrower Name' => '借入者',
    'Buy Date' => '購入日',
    'Categories' => 'カテゴリ一覧',
    'Category' => 'カテゴリ',
    'Category ID' => 'カテゴリID',
    'Code' => 'コード',
    'Contact' => '連絡',
    'Create Category' => 'カテゴリ追加',
    'Create Employee' => '社員追加',
    'Data Status' => 'データステータス',
    'Email' => 'メール',
    'Employee' => '会社員',
    'Employee ID' => '社員ID',
    'Employee No' => '社員番号',
    'Employees' => '社員一覧',
    'Equipment' => '設備',
    'Equipment ID' => '設備ID',
    'Equipment Status' => '設備ステータス',
    'Home' => 'ホーム',
	
    'ID' => 'ID',
    'Ignore' => '無視',
    'Lending' => '貸出履歴',
    'Lending Date' => '貸出日',
    'Login' => 'ログイン',
    'Logout' => 'ログアウト',
    'Model Number' => 'モデル番号',
    'Name' => '製品名',
    'Password' => 'パスワード',
    'Payment Amount' => '金額',
    'Privileges' => '権限',
    'Remarks' => 'コメント',
    'Return Date' => '返却日',
    'Save' => '保存',
    'Serial Number' => 'セリアナンバー',
    'Specification' => '特徴',
    'System User' => 'ユーザー管理',
    'Update Category: ' => 'カテゴリ編集',
    'Username' => 'ユーザー名',
    'Working Status' => '在籍状況',
    'Accessory' => '',
    'Auth Key' => '',
    'Create System User' => 'ユーザー追加',
    'Lending Histories' => '貸出履歴',
    'Equipment Management' => '設備管理システム',
    'Register'=>'ユーザー登録',
    'Name'=>'名前',
    
    'カテゴリ' => '@@@@',
    'コメント' => '@@@@',
    'コード' => '@@@@',
    'セリアナンバー' => '@@@@',
    'モデル番号' => '@@@@',
    '付属品' => '@@@@',
    '特徴' => '@@@@',
    '製品名' => '@@@@',
    '設備ステータス' => '@@@@',
    '購入日' => '@@@@',
    '金額' => '@@@@',
];
