<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Accessory' => '',
    'Auth Key' => '',
    'Borrower Name' => '',
    'Buy Date' => '',
    'Categories' => '',
    'Category' => '',
    'Category ID' => '',
    'Code' => '',
    'Contact' => '',
    'Create Category' => '',
    'Create Employee' => '',
    'Create System User' => '',
    'Data Status' => '',
    'Email' => '',
    'Employee' => '',
    'Employee ID' => '',
    'Employee No' => '',
    'Employees' => '',
    'Equipment' => '',
    'Equipment ID' => '',
    'Equipment Status' => '',
    'Home' => '',
    'ID' => '',
    'Ignore' => '',
    'Lending' => '',
    'Lending Date' => '',
    'Lending Histories' => '',
    'Login' => '',
    'Logout' => '',
    'Model Number' => '',
    'Name' => '',
    'Password' => '',
    'Payment Amount' => '',
    'Privileges' => '',
    'Remarks' => '',
    'Return Date' => '',
    'Save' => '',
    'Serial Number' => '',
    'Specification' => '',
    'System User' => '',
    'Update Category: ' => '',
    'Username' => '',
    'Working Status' => '',
    'カテゴリ' => '@@@@',
    'コメント' => '@@@@',
    'コード' => '@@@@',
    'セリアナンバー' => '@@@@',
    'モデル番号' => '@@@@',
    '付属品' => '@@@@',
    '特徴' => '@@@@',
    '製品名' => '@@@@',
    '設備ステータス' => '@@@@',
    '購入日' => '@@@@',
    '金額' => '@@@@',
];
